$( document ).ready(function() {
    		$("body *").replaceText(/ tår /g,' tär ');
	   		$("body *").replaceText(/ mina /g,' mia ');
    		$("body *").replaceText(/ och /g,' å ');
    		$("body *").replaceText(/ skulle /g,' sulle ');
    		$("body *").replaceText(/ väl /g,' la ');
    		$("body *").replaceText(/ världen /g,' väla ');
    		$("body *").replaceText(/ ute i /g,' uti ');
    		$("body *").replaceText(/ henne /g,' na ');
    		$("body *").replaceText(/ honom|man /g,' en ');
    		$("body *").replaceText(/ gick /g,' geck ');
    		$("body *").replaceText(/ gök /g,' gôk ');
    		$("body *").replaceText(/ ryggen /g,' rygga ');
    		$("body *").replaceText(/ röven /g,' räva ');
    		$("body *").replaceText(/ röv /g,' rôv ');
    		$("body *").replaceText(/ slog /g,' slo ');
    		$("body *").replaceText(/ ful /g,' rälier ');
    		$("body *").replaceText(/ ben /g,' skånker ');
    		$("body *").replaceText(/ sig /g,' sek ');
    		$("body *").replaceText(/ sliten /g,' sleten ');
    		$("body *").replaceText(/ slitna /g,' sletna ');
    		$("body *").replaceText(/ vara /g,' va ');
    		$("body *").replaceText(/ var /g,' va ');
    		$("body *").replaceText(/ några /g,' nåra ');
    		$("body *").replaceText(/ ska /g,' sa ');
    		$("body *").replaceText(/ måndagen /g,' måndan ');
    		$("body *").replaceText(/ tisdagen /g,' tisdan ');
  			$("body *").replaceText(/ onsdagen /g,' onsdan ');
  			$("body *").replaceText(/ torsdagen /g,' torsdan ');
  			$("body *").replaceText(/ fredagen /g,' fredan ');
  			$("body *").replaceText(/ lördagen /g,' lördan ');
  			$("body *").replaceText(/ söndagen /g,' söndan ');
    		$("body *").replaceText(/ fåglar /g,' fåggla ');
    		$("body *").replaceText(/ mig /g,' mek ');
    		$("body *").replaceText(/ äckliga /g,' sytlia ');
    		$("body *").replaceText(/ skräp /g,' bös ');
    		$("body *").replaceText(/ inom /g,' inum ');
    		$("body *").replaceText(/ mycket /g,' mö ');
    		$("body *").replaceText(/ rejält /g,' redit ');
    		$("body *").replaceText(/ tur /g,' röta ');
    		$("body *").replaceText(/ förlorade /g,' förlora ');
    		$("body *").replaceText(/ dina /g,' dia ');
    		$("body *").replaceText(/ Dina /g,' Dia ');
    		$("body *").replaceText(/ Någon /g,' Nån ');
    		$("body *").replaceText(/ någon /g,' nån ');
    		$("body *").replaceText(/ något /g,' nått ');
    		$("body *").replaceText(/ Jag /g,' Ja ');
    		$("body *").replaceText(/Ulricehamn/g,'Uschleham');
    		$("body *").replaceText(/ Ulricehamn /g,' Uschleham ');
    		$("body *").replaceText(/ ulricehamn /g,' uschleham ');
    		$("body *").replaceText(/ ulricehamnare /g,' uschlehamnare ');
    		$("body *").replaceText(/ Ulricehamns /g,' Uschlehams ');
    		$("body *").replaceText(/Tingsholm/g,'Tingshôlm');
    		$("body *").replaceText(/ Tingsholms /g,' Tingshôlms ');
    		$("body *").replaceText(/ skriven /g,' skreven ');
    		$("body *").replaceText(/ vanlig /g,' vanlier ');
    		$("body *").replaceText(/ mellan /g,' mälla ');
    		$("body *").replaceText(/ innan /g,' inna ');
    		$("body *").replaceText(/ drivna /g,' drevna ');
    		$("body *").replaceText(/ klockan /g,' klocka ');
    		$("body *").replaceText(/ från /g,' frå ');
    		$("body *").replaceText(/ låg /g,' lå ');
    		$("body *").replaceText(/ trycka /g,' tröka ');
    		$("body *").replaceText(/ kindbo /g,' kinnbo ');
    		$("body *").replaceText(/ Tidaholm /g,' Tiahölm ');
    		$("body *").replaceText(/ jag /g,' ja ');
    		$("body *").replaceText(/ Jag /g,' Ja ');
    		$("body *").replaceText(/ jag/g,' ja');
    		$("body *").replaceText(/Jag /g,'Ja ');
    		$("body *").replaceText(/ urinera /g,' hälla å pess ');
    		$("body *").replaceText(/ dig /g,' dek ');
    		$("body *").replaceText(/ till /g,' te ');
    		$("body *").replaceText(/ Till /g,' Te ');
    		$("body *").replaceText(/ vill /g,' vell ');
    		$("body *").replaceText(/bredvid/g,' brevé');
    		$("body *").replaceText(/Bredvid /g,'Jämte ');
    		$("body *").replaceText(/ som /g,' sum ');
    		$("body *").replaceText(/ Som /g,'Sum ');
    		$("body *").replaceText(/ om /g,' um ');
    		$("body *").replaceText(/ Om /g,' Um ');
    		$("body *").replaceText(/ vägarna /g,' väga ');
    		$("body *").replaceText(/ Vägarna /g,' Väga ');
    		$("body *").replaceText(/ det /g,' dä ');
    		$("body *").replaceText(/ Det /g,' Dä ');
    		$("body *").replaceText(/ är /g,' ä ');
    		$("body *").replaceText(/ Är /g,' Ä ');
    		$("body *").replaceText(/ bort /g,' bört ');
    		$("body *").replaceText(/ Bort /g,' Bört ');
    		$("body *").replaceText(/ hända /g,' hänna ');
    		$("body *").replaceText(/ av /g,' å ');
    		$("body *").replaceText(/ med /g,' mä ');
    		$("body *").replaceText(/ igenom /g,' igenum ');
    		$("body *").replaceText(/ vid /g,' ve ');
    		$("body *").replaceText(/ Vid /g,' Ve ');
    		$("body *").replaceText(/ efter /g,' ätter ');
    		$("body *").replaceText(/ Ätter /g,' Ätter ');
    		$("body *").replaceText(/ eftermiddag /g,' ättermedda ');
    		$("body *").replaceText(/ intill /g,' in\'te ');
    		$("body *").replaceText(/ dagar /g,' dar ');
    		$("body *").replaceText(/ Väder /g,' Vär ');
    		$("body *").replaceText(/ väder /g,' vär ');
    		$("body *").replaceText(/ visst /g,' vesst ');
    		$("body *").replaceText(/ Visst /g,' Vesst ');
    		$("body *").replaceText(/ twitter /g,' twetter ');
    		$("body *").replaceText(/ Twitter /g,' Twetter ');
    		$("body *").replaceText(/ brevlåda /g,' brevlôa ');
    		$("body *").replaceText(/ låda /g,' lôa ');
    		$("body *").replaceText(/ från /g,' frå ');
    		$("body *").replaceText(/från /g,'frå ');
    		$("body *").replaceText(/Från /g,'Frå ');
    		$("body *").replaceText(/ spegelblank /g,' spegelblanker ');
    		$("body *").replaceText(/ vägen /g,' väga ');
    		$("body *").replaceText(/Vägen /g,'Väga ');
    		$("body *").replaceText(/ jobb /g,' jôbb ');
    		$("body *").replaceText(/ Jôbb /g,' Jôbb ');
    		$("body *").replaceText(/Jôbb /g,'Jôbb ');
    		$("body *").replaceText(/ hund /g,' hunn ');
    		$("body *").replaceText(/Arbetsförmedlingen/g,'Arbetsfôrmeddlinga');
    		$("body *").replaceText(/Cityföreningen/g,'Cityföreninga');
    		$("body *").replaceText(/Gällstad/g,'Gällsta');
    		$("body *").replaceText(/Tvärred/g,'Tvärre');
    		$("body *").replaceText(/Vegby/g,'Veggby');
    		$("body *").replaceText(/Blidsberg/g,'Blissberg');
    		$("body *").replaceText(/ Nittorp /g,' Nettarp ');
    		$("body *").replaceText(/ trakten /g,' trakta ');
    		$("body *").replaceText(/ blev /g,' ble ');
    		$("body *").replaceText(/ kommunen /g,' kommun ');
    		$("body *").replaceText(/ under /g,' unner ');
    		$("body *").replaceText(/ turister /g,' turistera ');
    		$("body *").replaceText(/ välkommen /g,' välkummen ');
    		$("body *").replaceText(/ Välkommen /g,' Välkummen ');
    		$("body *").replaceText(/ vädret /g,' värt ');
    		$("body *").replaceText(/ Vädret /g,' Värt ');
    		$("body *").replaceText(/ att /g,' å ');
    		$("body *").replaceText(/ Växeln /g,' Växla ');
    		$("body *").replaceText(/ växeln /g,' växla ');
    		$("body *").replaceText(/ Växel /g,' Växla ');
    		$("body *").replaceText(/ växel /g,' växla ');
    		$("html *").replaceText(/ Krönikor /g,' Kröniker ');
    		$("body *").replaceText(/ krönikor /g,' kröniker ');
    		$("body *").replaceText(/ Skicka /g,' Skecka ');
    		$("body *").replaceText(/ skicka /g,' skecka ');
});