$( document ).ready(function() {
    		$("html *").replaceText(/ tår /g,' tär ');
	   		$("html *").replaceText(/ mina /g,' mia ');
    		$("html *").replaceText(/ och /g,' å ');
    		$("html *").replaceText(/ skulle /g,' sulle ');
    		$("html *").replaceText(/ väl /g,' la ');
    		$("html *").replaceText(/ världen /g,' väla ');
    		$("html *").replaceText(/ ute i /g,' uti ');
    		$("html *").replaceText(/ henne /g,' na ');
    		$("html *").replaceText(/ honom|man /g,' en ');
    		$("html *").replaceText(/ gick /g,' geck ');
    		$("html *").replaceText(/ gök /g,' gôk ');
    		$("html *").replaceText(/ ryggen /g,' rygga ');
    		$("html *").replaceText(/ röven /g,' räva ');
    		$("html *").replaceText(/ röv /g,' rôv ');
    		$("html *").replaceText(/ slog /g,' slo ');
    		$("html *").replaceText(/ ful /g,' rälier ');
    		$("html *").replaceText(/ ben /g,' skånker ');
    		$("html *").replaceText(/ sig /g,' sek ');
    		$("html *").replaceText(/ sliten /g,' sleten ');
    		$("html *").replaceText(/ slitna /g,' sletna ');
    		$("html *").replaceText(/ vara /g,' va ');
    		$("html *").replaceText(/ var /g,' va ');
    		$("html *").replaceText(/ sedan /g,' sen ');
    		$("html *").replaceText(/ några /g,' nåra ');
    		$("html *").replaceText(/ människor /g,' människer ');
    		$("html *").replaceText(/ oss /g,' uss ');
    		$("html *").replaceText(/ ska /g,' sa ');
    		$("html *").replaceText(/ tiden /g,' tia ');
    		$("html *").replaceText(/ tid /g,' ti ');
    		$("html *").replaceText(/ måndagen /g,' måndan ');
    		$("html *").replaceText(/ tisdagen /g,' tisdan ');
  			$("html *").replaceText(/ onsdagen /g,' onsdan ');
  			$("html *").replaceText(/ torsdagen /g,' torsdan ');
  			$("html *").replaceText(/ fredagen /g,' fredan ');
  			$("html *").replaceText(/ lördagen /g,' lördan ');
  			$("html *").replaceText(/ söndagen /g,' söndan ');
    		$("html *").replaceText(/ fåglar /g,' fåggla ');
    		$("html *").replaceText(/ mig /g,' mek ');
    		$("html *").replaceText(/ äckliga /g,' sytlia ');
    		$("html *").replaceText(/ skräp /g,' bös ');
    		$("html *").replaceText(/ inom /g,' inum ');
    		$("html *").replaceText(/ mycket /g,' mö ');
    		$("html *").replaceText(/ rejält /g,' redit ');
    		$("html *").replaceText(/ tur /g,' röta ');
    		$("html *").replaceText(/ förlorade /g,' förlora ');
    		$("html *").replaceText(/ dina /g,' dia ');
    		$("html *").replaceText(/ Dina /g,' Dia ');
    		$("html *").replaceText(/ Någon /g,' Nån ');
    		$("html *").replaceText(/ någon /g,' nån ');
    		$("html *").replaceText(/ något /g,' nått ');
    		$("html *").replaceText(/ Jag /g,' Ja ');
    		$("html *").replaceText(/Ulricehamn/g,'Uschleham');
    		$("html *").replaceText(/ Ulricehamn /g,' Uschleham ');
    		$("html *").replaceText(/ ulricehamn /g,' uschleham ');
    		$("html *").replaceText(/ ulricehamnare /g,' uschlehamnare ');
    		$("html *").replaceText(/Ulricehamns /g,'Uschlehams ');
    		$("html *").replaceText(/ Ulricehamns /g,' Uschlehams ');
    		$("html *").replaceText(/Tingsholm/g,'Tingshôlm');
    		$("html *").replaceText(/ Tingsholms /g,' Tingshôlms ');
    		$("html *").replaceText(/ skriven /g,' skreven ');
    		$("html *").replaceText(/ vanlig /g,' vanlier ');
    		$("html *").replaceText(/ mellan /g,' mälla ');
    		$("html *").replaceText(/ innan /g,' inna ');
    		$("html *").replaceText(/ drivna /g,' drevna ');
    		$("html *").replaceText(/ klockan /g,' klocka ');
    		$("html *").replaceText(/ från /g,' frå ');
    		$("html *").replaceText(/ låg /g,' lå ');
    		$("html *").replaceText(/ trycka /g,' tröka ');
    		$("html *").replaceText(/ kindbo /g,' kinnbo ');
    		$("html *").replaceText(/ Tidaholm /g,' Tiahölm ');
    		$("html *").replaceText(/Tidaholm /g,'Tiahölm ');
    		$("html *").replaceText(/ jag /g,' ja ');
    		$("html *").replaceText(/ Jag /g,' Ja ');
    		$("html *").replaceText(/ jag/g,' ja');
    		$("html *").replaceText(/Jag /g,'Ja ');
    		$("html *").replaceText(/ urinera /g,' hälla å pess ');
    		$("html *").replaceText(/ dig /g,' dek ');
    		$("html *").replaceText(/ till /g,' te ');
    		$("html *").replaceText(/ Till /g,' Te ');
    		$("html *").replaceText(/ vill /g,' vell ');
    		$("html *").replaceText(/bredvid/g,' breve');
    		$("html *").replaceText(/Bredvid /g,'Jämte ');
    		$("html *").replaceText(/ som /g,' sum ');
    		$("html *").replaceText(/ Som /g,'Sum ');
    		$("html *").replaceText(/ om /g,' um ');
    		$("html *").replaceText(/ Om /g,' Um ');
    		$("html *").replaceText(/ vägarna /g,' väga ');
    		$("html *").replaceText(/Vägarna /g,'Väga ');
    		$("html *").replaceText(/ det /g,' dä ');
    		$("html *").replaceText(/ Det /g,' Dä ');
    		$("html *").replaceText(/ är /g,' ä ');
    		$("html *").replaceText(/ Är /g,' Ä ');
    		$("html *").replaceText(/ bort /g,' bört ');
    		$("html *").replaceText(/Bort /g,'Bört ');
    		$("html *").replaceText(/ hända /g,' hänna ');
    		$("html *").replaceText(/ av /g,' å ');
    		$("html *").replaceText(/ med /g,' mä ');
    		$("html *").replaceText(/ igenom /g,' igenum ');
    		$("html *").replaceText(/ hitta /g,' hetta ');
    		$("html *").replaceText(/ vid /g,' ve ');
    		$("html *").replaceText(/ Vid /g,' Ve ');
    		$("html *").replaceText(/ efter /g,' ätter ');
    		$("html *").replaceText(/Efter /g,'Ätter ');
    		$("html *").replaceText(/ eftermiddag /g,' ättermedda ');
    		$("html *").replaceText(/ intill /g,' in\'te ');
    		$("html *").replaceText(/ dagar /g,' dar ');
    		$("html *").replaceText(/ fick /g,' feck ');
    		$("html *").replaceText(/ en /g,' ena ');
    		$("html *").replaceText(/ läsarna /g,' läsara ');
    		$("html *").replaceText(/ kvinna /g,' kvenna ');
    		$("html *").replaceText(/ kvinnor /g,' kvinner ');
    		$("html *").replaceText(/ Väder /g,' Vär ');
    		$("html *").replaceText(/ väder /g,' vär ');
    		$("html *").replaceText(/ visst /g,' vesst ');
    		$("html *").replaceText(/ Visst /g,' Vesst ');
    		$("html *").replaceText(/ twitter /g,' twetter ');
    		$("html *").replaceText(/ Twitter /g,' Twetter ');
    		$("html *").replaceText(/Twitter /g,'Twetter ');
    		$("html *").replaceText(/ brevlåda /g,' brevlôa ');
    		$("html *").replaceText(/ låda /g,' lôa ');
    		$("html *").replaceText(/ från /g,' frå ');
    		$("html *").replaceText(/från /g,'frå ');
    		$("html *").replaceText(/Från /g,'Frå ');
    		$("html *").replaceText(/ spegelblank /g,' spegelblanker ');
    		$("html *").replaceText(/ vägen /g,' väga ');
    		$("html *").replaceText(/Vägen /g,'Väga ');
    		$("html *").replaceText(/ jobb /g,' jôbb ');
    		$("html *").replaceText(/ Jôbb /g,' Jôbb ');
    		$("html *").replaceText(/Jôbb /g,'Jôbb ');
    		$("html *").replaceText(/Hund /g,'Hunn ');
    		$("html *").replaceText(/ hund /g,' hunn ');
    		$("html *").replaceText(/Arbetsförmedlingen/g,'Arbetsfôrmeddlinga');
    		$("html *").replaceText(/Cityföreningen/g,'Cityföreninga');
    		$("html *").replaceText(/Gällstad/g,'Gällsta');
    		$("html *").replaceText(/Tvärred/g,'Tvärre');
    		$("html *").replaceText(/Vegby/g,'Veggby');
    		$("html *").replaceText(/Blidsberg/g,'Blissberg');
    		$("html *").replaceText(/Nitta/g,'Netta');
    		$("html *").replaceText(/Nittorp/g,'Nettarp');
    		$("html *").replaceText(/ trakten /g,' trakta ');
    		$("html *").replaceText(/ blev /g,' ble ');
    		$("html *").replaceText(/ kommunen /g,' kommun ');
    		$("html *").replaceText(/ under /g,' unner ');
    		$("html *").replaceText(/ turister /g,' turistera ');
    		$("html *").replaceText(/ välkommen /g,' välkummen ');
    		$("html *").replaceText(/Välkommen/g,'Välkummen');
    		$("html *").replaceText(/Välkommen /g,'Välkummen ');
    		$("html *").replaceText(/ Välkommen /g,' Välkummen ');
    		$("html *").replaceText(/ vädret /g,' värt ');
    		$("html *").replaceText(/ Vädret /g,' Värt ');
    		$("html *").replaceText(/ att /g,' å ');
    		$("html *").replaceText(/ gammal /g,' gammel ');
    		$("html *").replaceText(/Växeln /g,'Växla ');
    		$("html *").replaceText(/ växeln /g,' växla ');
    		$("html *").replaceText(/ Växel /g,' Växla ');
    		$("html *").replaceText(/ växel /g,' växla ');
    		$("html *").replaceText(/Krönikor /g,'Kröniker ');
    		$("html *").replaceText(/ krönikor /g,' kröniker ');
    		$("html *").replaceText(/Skicka /g,'Skecka ');
    		$("html *").replaceText(/ skicka /g,' skecka ');
});