kindbo = function() {
    		$("body *").replaceText(/ tår /g,' tär ');
	   		$("body *").replaceText(/ mia /g,' mia ');
    		$("body *").replaceText(/ Ã¥ /g,' å ');
    		$("body *").replaceText(/ sulle /g,' sulle ');
    		$("body *").replaceText(/ väl /g,' la ');
    		$("body *").replaceText(/ världen /g,' väla ');
    		$("body *").replaceText(/ uti /g,' uti ');
    		$("body *").replaceText(/ na /g,' na ');
    		$("body *").replaceText(/ en | en /g,' en ');
    		$("body *").replaceText(/ gök /g,' gôk ');   		
    		$("body *").replaceText(/ röven /g,' räva ');
    		$("body *").replaceText(/ röv /g,' rôv ');   		
    		$("body *").replaceText(/ rÃ¤lier /g,' rälier ');
    		$("body *").replaceText(/ skÃ¥nker /g,' skånker ');
    		$("body *").replaceText(/ sek /g,' sek ');
    		$("body *").replaceText(/ sleten /g,' sleten ');
    		$("body *").replaceText(/ sletna /g,' sletna ');
    		$("body *").replaceText(/ va /g,' va ');
    		$("body *").replaceText(/ va /g,' va ');
    		$("body *").replaceText(/ några /g,' nåra ');
    		$("body *").replaceText(/ sa /g,' sa ');  		
    		$("body *").replaceText(/ fåglar /g,' fåggla ');
    		$("body *").replaceText(/ mek /g,' mek ');
    		$("body *").replaceText(/ äckliga /g,' sytlia ');
    		$("body *").replaceText(/ skräp /g,' bös ');
    		$("body *").replaceText(/ inum /g,' inum ');
    		$("body *").replaceText(/ mÃ¶ /g,' mö ');
    		$("body *").replaceText(/ rejält /g,' redit ');
    		$("body *").replaceText(/ rÃ¶ta /g,' röta ');    		
    		$("body *").replaceText(/ dia /g,' dia ');
    		$("body *").replaceText(/ Dia /g,' Dia ');
    		$("body *").replaceText(/ Någon /g,' Nån ');
    		$("body *").replaceText(/ någon /g,' nån ');
    		$("body *").replaceText(/ något /g,' nått ');
    		$("body *").replaceText(/ Ja /g,' Ja ');
    		$("body *").replaceText(/Uschleham/g,'Uschleham');
    		$("body *").replaceText(/ Uschleham /g,' Uschleham ');
    		$("body *").replaceText(/ uschleham /g,' uschleham ');
    		$("body *").replaceText(/ uschlehamnare /g,' uschlehamnare ');
    		$("body *").replaceText(/ Uschlehams /g,' Uschlehams ');
    		$("body *").replaceText(/TingshÃ´lm/g,'Tingshôlm');
    		$("body *").replaceText(/ TingshÃ´lms /g,' Tingshôlms ');
    		$("body *").replaceText(/ skreven /g,' skreven ');
    		$("body *").replaceText(/ vanlier /g,' vanlier ');
    		$("body *").replaceText(/ mÃ¤lla /g,' mälla ');
    		$("body *").replaceText(/ inna /g,' inna ');
    		$("body *").replaceText(/ drevna /g,' drevna ');
    		$("body *").replaceText(/ klocka /g,' klocka ');
    		$("body *").replaceText(/ från /g,' frå ');
    		$("body *").replaceText(/ låg /g,' lå ');
    		$("body *").replaceText(/ trÃ¶ka /g,' tröka ');
    		$("body *").replaceText(/ kinnbo /g,' kinnbo ');	
    		$("body *").replaceText(/ ja /g,' ja ');
    		$("body *").replaceText(/ Ja /g,' Ja ');
    		$("body *").replaceText(/ ja/g,' ja');
    		$("body *").replaceText(/Ja /g,'Ja ');
    		$("body *").replaceText(/ hälla Ã¥ pess /g,' hälla å pess ');
    		$("body *").replaceText(/ dek /g,' dek ');
    		$("body *").replaceText(/ te /g,' te ');
    		$("body *").replaceText(/ Te /g,' Te '); 		
    		$("body *").replaceText(/ brevid/g,' brevé');
    		$("body *").replaceText(/JÃ¤mte /g,'Jämte ');
    		$("body *").replaceText(/ sum /g,' sum ');
    		$("body *").replaceText(/Sum /g,'Sum ');
    		$("body *").replaceText(/ um /g,' um ');
    		$("body *").replaceText(/ Um /g,' Um ');
    		$("body *").replaceText(/ vägarna /g,' väga ');
    		$("body *").replaceText(/ Vägarna /g,' Väga ');
    		$("body *").replaceText(/ dÃ¤ /g,' dä ');
    		$("body *").replaceText(/ DÃ¤ /g,' Dä ');
    		$("body *").replaceText(/ är /g,' ä ');
    		$("body *").replaceText(/ Är /g,' Ä ');
    		$("body *").replaceText(/ bÃ¶rt /g,' bört ');
    		$("body *").replaceText(/ BÃ¶rt /g,' Bört ');
    		$("body *").replaceText(/ hända /g,' hänna ');
    		$("body *").replaceText(/ Ã¥ /g,' å ');
    		$("body *").replaceText(/ mÃ¤ /g,' mä ');
    		$("body *").replaceText(/ igenum /g,' igenum ');
    		$("body *").replaceText(/ ve /g,' ve ');
    		$("body *").replaceText(/ Ve /g,' Ve ');
    		$("body *").replaceText(/ Ã¤tter /g,' ätter ');
    		$("body *").replaceText(/ Ätter /g,' Ätter ');
    		$("body *").replaceText(/ Ã¤ttermedda /g,' ättermedda ');
    		$("body *").replaceText(/ in'te /g,' in\'te ');
    		$("body *").replaceText(/ dar /g,' dar ');
    		$("body *").replaceText(/ Väder /g,' Vär ');
    		$("body *").replaceText(/ väder /g,' vär ');
    		$("body *").replaceText(/ vesst /g,' vesst ');
    		$("body *").replaceText(/ Vesst /g,' Vesst ');
    		$("body *").replaceText(/ twetter /g,' twetter ');
    		$("body *").replaceText(/ Twetter /g,' Twetter ');
    		$("body *").replaceText(/ brevlåda /g,' brevlôa ');
    		$("body *").replaceText(/ låda /g,' lôa ');
    		$("body *").replaceText(/ från /g,' frå ');
    		$("body *").replaceText(/från /g,'frå ');
    		$("body *").replaceText(/Från /g,'Frå ');
    		$("body *").replaceText(/ spegelblanker /g,' spegelblanker ');
    		$("body *").replaceText(/ vägen /g,' väga ');
    		$("body *").replaceText(/Vägen /g,'Väga ');
    		$("body *").replaceText(/ jÃ´bb /g,' jôbb ');
    		$("body *").replaceText(/ Jôbb /g,' Jôbb ');
    		$("body *").replaceText(/Jôbb /g,'Jôbb ');   	
    		$("body *").replaceText(/Arbetsförmedlingen/g,'Arbetsfôrmeddlinga');
    		$("body *").replaceText(/Cityföreningen/g,'Cityföreninga');
    		$("body *").replaceText(/Gällstad/g,'Gällsta');
    		$("body *").replaceText(/Tvärred/g,'Tvärre');
    		$("body *").replaceText(/Veggby/g,'Veggby');
    		$("body *").replaceText(/Blissberg/g,'Blissberg');	
    		$("body *").replaceText(/ trakta /g,' trakta ');
    		$("body *").replaceText(/ ble /g,' ble ');
    		$("body *").replaceText(/ kommun /g,' kommun ');
    		$("body *").replaceText(/ unner /g,' unner ');
    		$("body *").replaceText(/ turistera /g,' turistera ');
    		$("body *").replaceText(/ välkommen /g,' välkummen ');
    		$("body *").replaceText(/ Välkommen /g,' Välkummen ');
};